//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;    
namespace CanTeenVLU.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.FOODs = new HashSet<FOOD>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Bắt buộc phải nhập")]
        [MinLength(5, ErrorMessage = "Nhập tối thiểu 5 kí tự")]
        [MaxLength(50, ErrorMessage = "Nhập tối đa 50 kí tự")]
        public string CATEGORY_CODE { get; set; }

        [Required(ErrorMessage = "Bắt buộc phải điền")]
        [MinLength(6, ErrorMessage = "Nhập tối thiểu 6 kí tự")]
        [MaxLength(20, ErrorMessage = " Nhập tối thiểu 20 kí tự")]
        public string CATEGORY_NAME { get; set; }
        
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOD> FOODs { get; set; }
    }
}
