//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace CanTeenVLU.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.MENUs = new HashSet<MENU>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Bắt buộc phải nhập")]
        [MinLength(2, ErrorMessage = "Nhập tối thiểu 2 kí tự")]
        [MaxLength(50, ErrorMessage = "Nhập tối đa 50 kí tự")]
        public string FOOD_CODE { get; set; }
        [Required(ErrorMessage = "Bắt buộc phải nhập")]
        [MinLength(6, ErrorMessage = "Nhập tối thiểu 6 kí tự")]
        [MaxLength(50, ErrorMessage = "Nhập tối đa 50 kí tự")]
        public string FOOD_NAME { get; set; }
        public int CATEGORY_ID { get; set; }
        [Required(ErrorMessage = "Bắt buộc phải nhập")]
        [MinLength(10, ErrorMessage = "Nhập tối thiểu 10 kí tự")]
        [MaxLength(10000, ErrorMessage = "Nhập tối đa 10000 kí tự")]
        public string DESCRIPTION { get; set; }
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Required(ErrorMessage = "Bắt buộc phải nhập")]
        [Range(100, 1000000, ErrorMessage = "Vui lòng điền 100 đến 1000000")]
        public int PRICE { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENUs { get; set; }
    }
}
